### ISSUE TITLE
Can't make install with CUDA

### ISSUE THREAD

**Issue by tsoernes** [ethereum-mining/ethminer#406]
Fedora 27
CUDA 8.0
GCC 7.2.1
After make with CUDA enabled, I do this: 
```
sudo make install
...
[ 54%] Built target ethcore
[ 57%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
/usr/lib/gcc/x86_64-redhat-linux/7/include/stddef.h(444): error: identifier "nullptr" is undefined
...
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00005e27_00000000-21_ethash_cuda_miner_kernel.compute_62.cpp1.ii".
Compilation terminated.
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:282 (message):
  Error generating file
  /home/torstein/code/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:407: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by MariusVanDerWijden** [comment]
Try compiling it with CUDA 9.0 
Ps. CUDA 9.0 only works with gcc 6.2.1 on fedora 
http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by tsoernes** [comment]
I think you're on track with the CUDA vs gcc version. I installed gcc54, which is compatible with CUDA 8, and did this
```
sudo cmake .. -DETHASHCUDA=ON -DCMAKE_CC_COMPILER='/home/torstein/gcc54/bin/gcc' -DCMAKE_CXX_COMPILER='/home/torstein/gcc54/bin/c++'
```
However I still get the same error, and note:
```
/usr/lib/gcc/x86_64-redhat-linux/7/include/stddef.h(444): error: identifier "nullptr" is undefined
/usr/lib/gcc/x86_64-redhat-linux/7/include/stddef.h(444): error: expected a ";"
/usr/include/c++/7/x86_64-redhat-linux/bits/c++config.h(2196): error: expected a ";"
/usr/include/c++/7/bits/exception.h(63): error: expected a ";"
```
It seems to be looking inside some directories belonging to system gcc, that is, version 7 (note the directories).

I don't know if there's much point trying CUDA9, since it's not compatible with gcc7 either.

Have I specified the c-compiler directory correctly? It seems that nvcc doesn't adhere to the cmake parameters.

**Comment by smurfy** [comment]
> I don't know if there's much point trying CUDA9, since it's not compatible with gcc7 either.

not sure about the gcc compatibility, but in the long run you need cuda9, because current master needs it.

Regarding the error, try: ``-DCUDA_NVCC_FLAGS='-std=c++11'". 
Strangly enougth, it works without any special flags on ubuntu with gcc 5.4

**Comment by chfast** [comment]
Can I close it?

**Comment by damienstanton** [comment]
Using these CC and CXX flags resolved any CUDA issues I ever saw, so I would close it.

**Comment by aigarius** [comment]
Documenting the correct form of CC and CXX variable in the README would be useful.
