### PR TITLE
set PLATFORM correctly.

### PR DESCRIPTION
**Pull request by hackmod**
set the `PLATFORM` as intended.

please see a5be252960a
fix regression bug caused by commit 5efd47caa0.

### CODE REVIEW

**Review by galkinvv — APPROVED** [review]
Tested this PR.

Before it on linux+amd mesa drivers cl compilation failed.
With it applied linux+amd mesa drivers cl compilation succeded, minig started (but shares found are incorrect, this seems the unrelated problem with clover)

**Comment by hackmod** [comment]
> Tested this PR.
> 
> Before it on linux+amd mesa drivers cl compilation failed.
> With it applied linux+amd mesa drivers cl compilation succeded, mining started (but shares found are incorrect, this seems the unrelated problem with clover)

yes. right. I've been tested recently with rx480/rx570 but the mesa-opencl does not work.
(I guess `libclc-amdgcn` have some issues)

**Review by jean-m-cyr — APPROVED** [review]

**Review by dustpan28645 — COMMENTED** [review]
Pan
