### ISSUE TITLE
Incompatible with Boost 1.7x

### ISSUE THREAD

**Issue by Atemu** [ethereum-mining/ethminer#2393]
**Describe the bug**

```
[ 73%] Built target ethash-cl
[ 76%] Building CXX object libethcore/CMakeFiles/ethcore.dir/EthashAux.cpp.o
[ 80%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Farm.cpp.o
[ 83%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Miner.cpp.o
In file included from /nix/store/d73chcglazgj5h9wsgksy1z1r383rixa-opencl-headers-2021.06.30/include/CL/cl.h:20,
                 from /nix/store/d73chcglazgj5h9wsgksy1z1r383rixa-opencl-headers-2021.06.30/include/CL/opencl.h:24,
                 from /build/source/libethcore/../libethash-cl/CL/cl2.hpp:504,
                 from /build/source/libethcore/../libethash-cl/CLMiner.h:27,
                 from /build/source/libethcore/Farm.cpp:22:
/nix/store/d73chcglazgj5h9wsgksy1z1r383rixa-opencl-headers-2021.06.30/include/CL/cl_version.h:22:104: note: '#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)'
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
/build/source/libethcore/Farm.cpp: In member function 'void dev::eth::Farm::restart_async()':
/build/source/libethcore/Farm.cpp:385:17: error: 'class boost::asio::io_context::strand' has no member named 'get_io_service'
  385 |     m_io_strand.get_io_service().post(m_io_strand.wrap(boost::bind(&Farm::restart, this)));
      |                 ^~~~~~~~~~~~~~
make[2]: *** [libethcore/CMakeFiles/ethcore.dir/build.make:90: libethcore/CMakeFiles/ethcore.dir/Farm.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:306: libethcore/CMakeFiles/ethcore.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Builds fine with Boost 1.6x.

**Comment by y001j** [comment]
fixed in #2396
