### ISSUE TITLE
Won't build on Ubuntu Server 20.04

### ISSUE THREAD

**Issue by thehack** [ethereum-mining/ethminer#2143]
**Describe the bug**
Cuda 11 branch will not build on Ubuntu Server Edition 20.04 due to gcc version.

**To Reproduce**
try to build following readme instructions

**Error Code**
[ 42%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:220 (message):
  Error generating
  /home/tim/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:65: libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:483: libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by mckunkel** [comment]
+1 same for me

**Comment by mckunkel** [comment]
I fixed this by chaning my GCC to 7.
Here's a link describing how to in 3 easy steps
[https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa](https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa)

**Comment by sirNugg3ts** [comment]
+1 here

**Comment by corrosivecamel** [comment]
> I fixed this by changing my GCC to 7.
> Here's a link describing how to in 3 easy steps
> https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa

Did you switch both GCC and G++ to 7 or just GCC?

**Comment by mckunkel** [comment]
> > I fixed this by changing my GCC to 7.
> > Here's a link describing how to in 3 easy steps
> > https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa
> 
> Did you switch both GCC and G++ to 7 or just GCC?

I had no need for gcc/g++ > 7, so I did both

**Comment by corrosivecamel** [comment]
Thank you mckunkel

**Comment by executionByFork** [comment]
If you use `update-alternatives` to switch gcc/g++ versions, make sure you
`cmake .. [CLI_FLAGS]`
before you
`cmake --build .`
again.

Heh. I was really confused why standard cpp libraries such as `std::basic_stringstream` weren't being found...

**Comment by mask8** [comment]
> from :
> /usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
> 138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!

This path indicates that you were probably using cuda-10.1 toolkit installed from Ubuntu repo.
If possible try the latest CUDA-11 from Nvidia repo here:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=debnetwork

The gcc version issue will probably be resolved.

**Comment by drfence** [comment]
I see the same complaint about gcc with CUDA 11.4 on Ubuntu 20.04 and using ethminer 0.18.

**Comment by drfence** [comment]
> This path indicates that you were probably using cuda-10.1 toolkit installed from Ubuntu repo.
> If possible try the latest CUDA-11 from Nvidia repo here:
> https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=debnetwork
> 
> The gcc version issue will probably be resolved.

@mask8 I have CUDA-11 installed but see the same unsupported GCC 8 message.   Why do you say it's a CUDA-10 related?

**Comment by drfence** [comment]
Thank you @mckunkel, I'll try downgrading gcc.
